import type { Metadata } from "next";
import { ConvexClientProvider } from "../components/web/ConvexClientProvider";
import { ThemeProvider } from "@/components/ui/theme-provider";
import { LanguageProvider } from "@/components/ui/language-provider";
import { Toaster } from "@/components/ui/sonner";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <body className="antialiased">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <LanguageProvider>
            <main className="max-w-7xl mx-auto px-4 md:px-6 lg:px-8">
              <ConvexClientProvider>{children}</ConvexClientProvider>
            </main>
            <Toaster closeButton />
          </LanguageProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
